language: rust
sudo: required
dist: bionic
matrix:
  include:
    - rust: nightly
      env:
       - CHANNEL='nightly'
env:
  global:
    - HOST=x86_64-unknown-linux-gnu
    - CARGO_INCREMENTAL=0
    - RUSTFLAGS="-Clink-arg=-fuse-ld=lld"
addons:
  apt:
    packages:
      - libopenblas-dev
      - gfortran
script:
  - ./scripts/all-tests.sh "$FEATURES" "$CHANNEL"
