language: rust
# use trusty for newer openblas
sudo: required
dist: trusty
matrix:
  include:
    - rust: 1.22.1
      env:
       - FEATURES='test'
    - rust: stable
      env:
       - FEATURES='test'
       - CARGO_INCREMENTAL=0
    - rust: beta
      env:
       - FEATURES='test'
       - CARGO_INCREMENTAL=0
    - rust: nightly
      env:
       - FEATURES='test'
       - IS_NIGHTLY=1
       - CARGO_INCREMENTAL=0
branches:
  only:
    - master
    - 0.10.x
addons:
  apt:
    packages:
      - libopenblas-dev
      - gfortran
script:
  - |
      ./scripts/all-tests.sh "$FEATURES" "$IS_NIGHTLY"
