[package]

name = "ndarray"
version = "0.0.1"
authors = ["bluss"]
repository = "https://github.com/bluss/rust-ndarray"
documentation = "http://bluss.github.io/rust-ndarray/"

[dependencies.num]

git = "https://github.com/rust-lang/num"

[dependencies.rustc-serialize]
version = "*"
optional = true

[dependencies.itertools]
version = "*"
features = ["unstable"]

[dependencies.serde]
version = "*"
optional = true

